apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/name: Bar
        app.kubernetes.io/signed: 'false'
        app.kubernetes.io/description: reject
      name: unsignedimage
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: Bar
      template:
        metadata:
          labels:
            app.kubernetes.io/name: Bar
        spec:
          containers:
            - name: bar
              image: ghcr.io/garethahealy/kyverno-unsigned:latest
